// Well-known ordinal-to-name mappings for DLLs that export by ordinal.
// Sources: Wine .spec files (dlls/<name>/<name>.spec) for the canonical ordinals
// shipped by Microsoft. WS2_32 ordinals are identical to WSOCK32's.
//
// Used at static-IAT thunk-build time (emu-thunks-pe.ts) AND at runtime
// GetProcAddress(hModule, MAKEINTRESOURCE(N)) to resolve ordinal imports of
// stub-only system DLLs to their real API names.

export const dllOrdinalMap: Record<string, Record<number, string>> = {
  'COMCTL32.DLL': {
    2: 'MenuHelp', 4: 'GetEffectiveClientRect',
    7: 'CreateToolbar', 8: 'CreateMappedBitmap', 17: 'InitCommonControls',
    71: 'ImageList_Create', 72: 'ImageList_Destroy', 73: 'ImageList_GetImageCount',
    74: 'ImageList_Add', 75: 'ImageList_ReplaceIcon', 76: 'ImageList_Remove',
    84: 'ImageList_SetBkColor', 85: 'ImageList_GetBkColor',
    236: 'Str_SetPtrW',
    329: 'DSA_Destroy', 337: 'DPA_DeletePtr', 338: 'DPA_DeleteAllPtrs', 340: 'DPA_CreateEx',
    320: 'CreatePropertySheetPageA', 321: 'CreatePropertySheetPageW',
    322: 'DestroyPropertySheetPage',
    334: 'PropertySheetA', 335: 'PropertySheetW',
    358: 'StrChrW', 359: 'StrRChrW', 363: 'StrStrIW', 365: 'StrToIntW',
    410: 'FlatSB_SetScrollProp', 413: 'FlatSB_SetScrollInfo',
  },
  'SHLWAPI.DLL': {
    219: 'SHLoadIndirectString',
    437: 'IsOS',
  },
  'SHELL32.DLL': {
    30: 'PathBuildRootA',
    34: 'PathRemoveBlanksA',
    36: 'PathAppendA',
    39: 'PathIsRelativeA',
    45: 'PathFileExistsA',
    61: 'ord_61',
    100: 'ord_100',
    183: 'ShellMessageBoxA',
    195: 'SHFree',
  },
  'WINMM.DLL': {
    2: 'PlaySoundA',
  },
  // WS2_32 (Microsoft) ordinals — identical to WSOCK32's classic numbering.
  'WS2_32.DLL': {
    1: 'accept', 2: 'bind', 3: 'closesocket', 4: 'connect',
    5: 'getpeername', 6: 'getsockname', 7: 'getsockopt',
    8: 'htonl', 9: 'htons', 10: 'ioctlsocket',
    11: 'inet_addr', 12: 'inet_ntoa', 13: 'listen',
    14: 'ntohl', 15: 'ntohs', 16: 'recv', 17: 'recvfrom',
    18: 'select', 19: 'send', 20: 'sendto', 21: 'setsockopt',
    22: 'shutdown', 23: 'socket',
    51: 'gethostbyaddr', 52: 'gethostbyname',
    53: 'getprotobyname', 54: 'getprotobynumber',
    55: 'getservbyname', 56: 'getservbyport', 57: 'gethostname',
    101: 'WSAAsyncSelect', 102: 'WSAAsyncGetHostByAddr',
    103: 'WSAAsyncGetHostByName', 104: 'WSAAsyncGetProtoByName',
    105: 'WSAAsyncGetProtoByNumber', 106: 'WSAAsyncGetServByName',
    107: 'WSAAsyncGetServByPort', 108: 'WSACancelAsyncRequest',
    109: 'WSASetBlockingHook', 110: 'WSAUnhookBlockingHook',
    111: 'WSAGetLastError', 112: 'WSASetLastError',
    113: 'WSACancelBlockingCall', 114: 'WSAIsBlocking',
    115: 'WSAStartup', 116: 'WSACleanup',
  },
  'WSOCK32.DLL': {
    1: 'accept', 2: 'bind', 3: 'closesocket', 4: 'connect',
    5: 'getpeername', 6: 'getsockname', 7: 'getsockopt',
    8: 'htonl', 9: 'htons', 10: 'ioctlsocket',
    11: 'inet_addr', 12: 'inet_ntoa', 13: 'listen',
    14: 'ntohl', 15: 'ntohs', 16: 'recv', 17: 'recvfrom',
    18: 'select', 19: 'send', 20: 'sendto', 21: 'setsockopt',
    22: 'shutdown', 23: 'socket',
    51: 'gethostbyaddr', 52: 'gethostbyname',
    53: 'getprotobyname', 54: 'getprotobynumber',
    55: 'getservbyname', 56: 'getservbyport', 57: 'gethostname',
    101: 'WSAAsyncSelect', 102: 'WSAAsyncGetHostByAddr',
    103: 'WSAAsyncGetHostByName', 104: 'WSAAsyncGetProtoByName',
    105: 'WSAAsyncGetProtoByNumber', 106: 'WSAAsyncGetServByName',
    107: 'WSAAsyncGetServByPort', 108: 'WSACancelAsyncRequest',
    109: 'WSASetBlockingHook', 110: 'WSAUnhookBlockingHook',
    111: 'WSAGetLastError', 112: 'WSASetLastError',
    113: 'WSACancelBlockingCall', 114: 'WSAIsBlocking',
    115: 'WSAStartup', 116: 'WSACleanup',
  },
  'COREDLL.DLL': {
    23: 'GetLocalTime',
    61: 'wcscpy', 63: 'wcslen',
    90: 'CreateDIBSection', 95: 'RegisterClassW',
    246: 'CreateWindowExW', 247: 'SetWindowPos', 248: 'GetWindowRect',
    250: 'InvalidateRect', 260: 'BeginPaint', 261: 'EndPaint',
    262: 'GetDC', 264: 'DefWindowProcW', 265: 'DestroyWindow',
    266: 'ShowWindow', 267: 'UpdateWindow',
    535: 'GetTickCount',
    708: 'SetCapture', 709: 'ReleaseCapture',
    858: 'MessageBoxW', 859: 'DispatchMessageW', 861: 'GetMessageW',
    865: 'PostMessageW', 866: 'PostQuitMessage', 870: 'TranslateMessage',
    873: 'LoadBitmapW', 874: 'LoadStringW', 875: 'SetTimer', 876: 'KillTimer',
    885: 'GetSystemMetrics', 895: 'CreateFontIndirectW',
    902: 'CreateCompatibleBitmap', 903: 'BitBlt',
    909: 'CreateDCW', 910: 'CreateCompatibleDC', 911: 'DeleteDC',
    912: 'DeleteObject', 918: 'GetObjectW', 919: 'GetStockObject',
    921: 'SelectObject', 923: 'SetBkMode', 924: 'SetTextColor',
    931: 'CreateSolidBrush', 933: 'DrawFocusRect', 936: 'GetPixel',
    941: 'Rectangle', 945: 'DrawTextW',
    968: 'CombineRgn', 980: 'CreateRectRgn',
    1018: 'free', 1041: 'malloc', 1047: 'memset', 1053: 'rand', 1061: 'srand',
    1097: 'swprintf', 1398: 'SetWindowRgn',
  },
  // OLEAUT32 ordinals from Wine spec (dlls/oleaut32/oleaut32.spec).
  'OLEAUT32.DLL': {
    2: 'SysAllocString', 3: 'SysReAllocString', 4: 'SysAllocStringLen',
    5: 'SysReAllocStringLen', 6: 'SysFreeString', 7: 'SysStringLen',
    8: 'VariantInit', 9: 'VariantClear', 10: 'VariantCopy',
    11: 'VariantCopyInd', 12: 'VariantChangeType', 13: 'VariantTimeToDosDateTime',
    14: 'DosDateTimeToVariantTime', 15: 'SafeArrayCreate', 16: 'SafeArrayDestroy',
    17: 'SafeArrayGetDim', 18: 'SafeArrayGetElemsize', 19: 'SafeArrayGetUBound',
    20: 'SafeArrayGetLBound', 21: 'SafeArrayLock', 22: 'SafeArrayUnlock',
    23: 'SafeArrayAccessData', 24: 'SafeArrayUnaccessData',
    25: 'SafeArrayGetElement', 26: 'SafeArrayPutElement',
    27: 'SafeArrayCopy', 28: 'DispGetParam', 29: 'DispGetIDsOfNames',
    30: 'DispInvoke', 31: 'CreateDispTypeInfo', 32: 'CreateStdDispatch',
    33: 'RegisterActiveObject', 34: 'RevokeActiveObject', 35: 'GetActiveObject',
    36: 'SafeArrayAllocDescriptor', 37: 'SafeArrayAllocData',
    38: 'SafeArrayDestroyDescriptor', 39: 'SafeArrayDestroyData',
    40: 'SafeArrayRedim', 41: 'SafeArrayAllocDescriptorEx',
    42: 'SafeArrayCreateEx', 43: 'SafeArrayCreateVectorEx',
    44: 'SafeArraySetRecordInfo', 45: 'SafeArrayGetRecordInfo',
    46: 'VarParseNumFromStr', 47: 'VarNumFromParseNum',
    48: 'VarI2FromUI1', 49: 'VarI2FromI4', 50: 'VarI2FromR4',
    147: 'VariantChangeTypeEx',
    149: 'SysAllocStringByteLen', 150: 'SysStringByteLen', 151: 'LoadTypeLib',
    160: 'LoadRegTypeLib', 161: 'RegisterTypeLib', 162: 'QueryPathOfRegTypeLib',
    183: 'OleCreateFontIndirect', 184: 'OleTranslateColor',
    185: 'OleCreatePictureIndirect', 186: 'OleLoadPicture',
    187: 'OleLoadPicturePath',
    420: 'VarBstrFromR4',
  },
  'OLEDLG.DLL': {
    2: 'OleUIAddVerbMenuA', 3: 'OleUIBusyA', 4: 'OleUICanConvertOrActivateAs',
    5: 'OleUIChangeIconA', 6: 'OleUIChangeSourceA', 7: 'OleUIConvertA',
    8: 'OleUIEditLinksA', 9: 'OleUIInsertObjectA', 10: 'OleUIObjectPropertiesA',
    11: 'OleUIPasteSpecialA', 12: 'OleUIPromptUserA', 13: 'OleUIUpdateLinksA',
    14: 'OleUIAddVerbMenuW', 15: 'OleUIBusyW', 16: 'OleUIChangeIconW',
    17: 'OleUIChangeSourceW', 18: 'OleUIConvertW', 19: 'OleUIEditLinksW',
    20: 'OleUIInsertObjectW', 21: 'OleUIObjectPropertiesW',
    22: 'OleUIPasteSpecialW', 23: 'OleUIPromptUserW', 24: 'OleUIUpdateLinksW',
  },
};

/** Resolve an ordinal → API name for a known stub DLL. Returns undefined when unknown. */
export function ordinalToName(dll: string, ordinal: number): string | undefined {
  return dllOrdinalMap[dll.toUpperCase()]?.[ordinal];
}
